# foo

In [2]:
import pandas as pd
df = pd.read_csv("world.csv")
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.951538,7.040657,2.234429,-2.496550,-25.793229,25.154964,8.912308,4.216132,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-2.132940,5.008777,2.794386,1.829575,2.245805,...,-0.467421,0.018464,-0.104064,-0.543715,-5.447021,1.829597,0.905330,-0.645084,0.256613,NaN
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.300121,-0.195570,-1.713743,0.856295,-5.382515,-22.584482,-7.576669,0.106093,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.251142,1.538396,4.741446,3.087620,1.823720,...,-2.448451,-0.355460,0.330192,0.792526,-3.321745,1.599746,1.578046,0.920848,1.707193,NaN
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.002649,-3.620758,-4.665970,-4.010017,-8.672076,-1.969591,-0.143628,-1.988293,1.292931,NaN

In [3]:
foo = df.transpose()
foo

,0,1,2,3,4,5,6,7,8,9,...,256,257,258,259,260,261,262,263,264,265
Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Viet Nam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Indicator Name,GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),...,GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %),GDP per capita growth (annual %)
Indicator Code,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,...,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG,NY.GDP.PCAP.KD.ZG
1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,25.154964,1.829597,-22.584482,1.599746,-1.969591,9.984331,6.927045,2.83541,2.457175,10.14856,...,4.07887,1.666516,-3.808557,5.535672,-7.876432,10.99814,NaN,3.350531,3.285755,6.611933
2022,8.912308,0.90533,-7.576669,1.578046,-0.143628,6.108948,7.721238,4.565308,2.176083,5.048195,...,-0.883384,7.725699,2.774357,2.460403,-5.958225,5.339098,NaN,0.48062,2.343365,4.343582
2023,4.216132,-0.645084,0.106093,0.920848,-1.988293,5.137124,1.123259,-0.759813,-0.421511,-1.89295,...,NaN,4.36195,-3.240622,1.991416,8.501973,9.351075,NaN,-0.630051,2.46464,3.584903
2024,NaN,0.256613,NaN,1.707193,1.292931,5.162522,2.006784,-0.610338,0.010374,-2.058403,...,NaN,6.417285,1.63021,1.889469,8.741783,15.032549,NaN,-0.669087,1.158387,0.228944
Unnamed: 69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN