# Normalizing data 

To be persited within RDMS, we will normalize given data

- [Original data set](https://www.kaggle.com/datasets/CooperUnion/cardataset)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
%matplotlib inline     
sns.set_theme(color_codes=True)

In [3]:
# Importing data 
df = pd.read_csv("dta/cardata/data_san.csv")

df.head(23)

,id,Make,Model,Year,Engine_Fuel_Type,Engine_HP,Engine_Cylinders,Transmission_Type,Driven_Wheels,Number_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,highway_MPG,city_mpg,Popularity,MSRP
0,1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
1,2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
2,3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
3,4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
4,5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
5,6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
6,7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
7,8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
8,9,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200
9,10,BMW,1 Series,2013,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39600
10,11,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
11,12,BMW,1 Series,2013,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,44400
12,13,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,19,3916,37200
13,14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
14,15,BMW,1 Series,2013,premium unleaded (required),320.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,25,18,3916,48250
15,16,BMW,1 Series,2013,premium unleaded (required),320.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,43550
16,17,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
17,18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
18,19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
19,20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,21,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,all wheel drive,4.0,Luxury,Midsize,Sedan,21,16,3105,2000
21,22,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
22,23,Audi,100,1993,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000

In [10]:
colz_old = df.columns
npath = "dta/norm/"
colz_old

Index(['Unnamed: 0', 'Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [15]:
brndz = pd.DataFrame(df["Make"].unique())
#brndz['id'] = 123 + df.index
brndz.to_csv(npath + 'brndz.csv')
brndz.head()

               0
0            BMW
1           Audi
2           FIAT
3  Mercedes-Benz
4       Chrysler

In [18]:
tmp = pd.read_csv(npath + 'brndz.csv')
tmp['id'] = 123 + tmp['rownum']

tmp.to_csv(npath + 'brndz_idc.csv', index=False)

tmp

/var/folders/sq/2n461t452vd6tvf2zfbm2jq00000gn/T/ipykernel_7576/2634209106.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  tmp['id'] = 123 + tmp['rownum']

    rownum          value   id
0        0            BMW  123
1        1           Audi  124
2        2           FIAT  125
3        3  Mercedes-Benz  126
4        4       Chrysler  127
5        5         Nissan  128
6        6          Volvo  129
7        7          Mazda  130
8        8     Mitsubishi  131
9        9        Ferrari  132
10      10     Alfa Romeo  133
11      11        McLaren  134
12      12        Maybach  135
13      13        Porsche  136
14      14         Toyota  137
15      15           Saab  138
16      16            GMC  139
17      17        Hyundai  140
18      18          Honda  141
19      19       Cadillac  142
20      20        Bentley  143
21      21           Ford  144
22      22     Oldsmobile  145
23      23      Chevrolet  146
24      24          Dodge  147
25      25    Lamborghini  148
26      26        Lincoln  149
27      27        Pontiac  150
28      28         Subaru  151
29      29     Volkswagen  152
30      30         Spyker  153
31      31            Kia  154
32      32          Acura  155
33      33       Plymouth  156
34      34    Rolls-Royce  157
35      35       Maserati  158
36      36          Lexus  159
37      37   Aston Martin  160
38      38     Land Rover  161
39      39          Lotus  162
40      40          Buick  163
41      41       Infiniti  164
42      42          Scion  165
43      43        Genesis  166
44      44         Suzuki  167
45      45         HUMMER  168
46      46        Bugatti  169

In [19]:
df.head()

,Unnamed: 0,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [5]:
from pyapml.normalize import Normalize

In [9]:
norm_colz = [
    "Engine Fuel Type",
    "Transmission Type",
    "Driven_Wheels",
    "Market Category",
    "Vehicle Size",
    "Vehicle Style",
    "Brndz",
]
sfx = ".csv"
npath = "dta/norm/"
for x in norm_colz:
    fn = npath + x.replace(" ", "") + sfx
    nw_nm = npath + Normalize.sanitize_name(x) + sfx
    print("mv", fn, nw_nm)
    # tmp = pd.DataFrame(df[x].unique())
    # tmp.to_csv(fn)

mv dta/norm/EngineFuelType.csv dta/norm/Engine_Fuel_Type.csv
mv dta/norm/TransmissionType.csv dta/norm/Transmission_Type.csv
mv dta/norm/Driven_Wheels.csv dta/norm/Driven_Wheels.csv
mv dta/norm/MarketCategory.csv dta/norm/Market_Category.csv
mv dta/norm/VehicleSize.csv dta/norm/Vehicle_Size.csv
mv dta/norm/VehicleStyle.csv dta/norm/Vehicle_Style.csv
mv dta/norm/Brndz.csv dta/norm/Brndz.csv

In [6]:
df.head()

,id,Make,Model,Year,Engine_Fuel_Type,Engine_HP,Engine_Cylinders,Transmission_Type,Driven_Wheels,Number_of_Doors,Market_Category,Vehicle_Size,Vehicle_Style,highway_MPG,city_mpg,Popularity,MSRP
0,1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
1,2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
2,3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
3,4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
4,5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200

In [13]:
m = df["Market_Category"].unique()


mc = []

for x in m:
    tmp = x.split(",")
    for y in tmp:
        mc.append(y)



uniq = set(mc)

print("\n".join(uniq))

Hybrid
Exotic
High-Performance
Factory Tuner
Performance
Hatchback
Diesel
Crossover
Flex Fuel
Luxury

In [17]:
mark = pd.read_csv("dta/norm/mar_k_v.csv")
mark["value"] = pow(2,mark["id"])
mark.to_csv("dta/norm/mkv.csv", index =False)

/var/folders/sq/2n461t452vd6tvf2zfbm2jq00000gn/T/ipykernel_11499/1932675076.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mark["value"] = pow(2,mark["id"])